export type {
  // Element types
  Element,
  BoxElement,
  FlexElement,
  TextElement,
  ImageElement,
  // Style types
  BoxStyle,
  FlexStyle,
  TextStyle,
  ImageStyle,
  // Primitive types
  Dimension,
  Spacing,
  BorderRadius,
  Color,
  FontWeight,
  FlexDirection,
  JustifyContent,
  AlignItems,
  FlexWrap,
  TextAlign,
  ObjectFit,
  // Document & compilation
  HtvgDocument,
  CompileOptions,
  CompileResult,
} from "./types.js";

import type { HtvgDocument, Element, CompileOptions, CompileResult } from "./types.js";

/**
 * Input types accepted by `init()`.
 *
 * - **Browser**: omit for auto-fetch, or pass a `URL`/`string` to the `.wasm` file
 * - **Node.js**: pass a `Buffer` from `fs.readFileSync("htvg_bg.wasm")`
 * - **Cloudflare Workers**: pass the imported `WebAssembly.Module`
 * - **Deno**: omit for auto-fetch, or pass a `URL`
 */
export type InitInput =
  | RequestInfo
  | URL
  | Response
  | BufferSource
  | WebAssembly.Module
  | Promise<Response>;

// WASM module types (generated by wasm-pack)
interface HtvgWasm {
  default: (input?: InitInput | { module_or_path: InitInput }) => Promise<void>;
  compileDocument: (docJson: string) => CompileResult;
  compile: (elementJson: string, optionsJson: string) => CompileResult;
  version: () => string;
}

let wasmModule: HtvgWasm | null = null;

async function loadWasm(): Promise<HtvgWasm> {
  return await import("./wasm/htvg.js" as string);
}

/**
 * Initialize the HTVG WASM module (async).
 * Must be called before any compilation functions.
 *
 * @example
 * // Browser — auto-fetches the .wasm file
 * await init();
 *
 * @example
 * // Node.js
 * import fs from "node:fs";
 * await init(fs.readFileSync("node_modules/htvg/wasm/htvg_bg.wasm"));
 *
 * @example
 * // Cloudflare Workers
 * import wasmModule from "./htvg_bg.wasm";
 * await init(wasmModule);
 */
export async function init(input?: InitInput): Promise<void> {
  if (wasmModule) return;

  const wasm = await loadWasm();
  await wasm.default(input);
  wasmModule = wasm;
}

function getWasm(): HtvgWasm {
  if (!wasmModule) {
    throw new Error("HTVG WASM not initialized. Call `await init()` first.");
  }
  return wasmModule;
}

/**
 * Compile a self-contained HTVG document to SVG.
 *
 * @param doc - An HtvgDocument object or a JSON string.
 * @returns Compilation result with SVG string and metadata.
 */
export function compileDocument(doc: HtvgDocument | string): CompileResult {
  const wasm = getWasm();
  const json = typeof doc === "string" ? doc : JSON.stringify(doc);
  return wasm.compileDocument(json);
}

/**
 * Compile an element tree with separate options.
 *
 * @param element - An Element object or a JSON string.
 * @param options - Compilation options.
 * @returns Compilation result with SVG string and metadata.
 */
export function compile(
  element: Element | string,
  options: CompileOptions
): CompileResult {
  const wasm = getWasm();
  const elementJson =
    typeof element === "string" ? element : JSON.stringify(element);
  const optionsJson = JSON.stringify(options);
  return wasm.compile(elementJson, optionsJson);
}

/**
 * Get the HTVG version string.
 */
export function version(): string {
  return getWasm().version();
}
