import { init, compileDocument, type HtvgDocument } from "htvg";
// @ts-ignore — wrangler handles .wasm imports natively
import wasmBinary from "htvg/htvg.wasm";

const doc: HtvgDocument = {
  meta: { width: 400 },
  content: {
    type: "flex",
    style: {
      width: 400,
      padding: 32,
      backgroundColor: "#ffffff",
      flexDirection: "column",
      gap: 12,
    },
    children: [
      {
        type: "text",
        content: "Hello from Cloudflare Workers!",
        style: { fontSize: 28, fontWeight: "bold", color: "#1a1a1a" },
      },
      {
        type: "text",
        content: "This SVG was generated by HTVG running as WASM inside a Worker.",
        style: { fontSize: 16, color: "#666666" },
      },
    ],
  },
};

export default {
  async fetch(request: Request): Promise<Response> {
    const url = new URL(request.url);

    await init(wasmBinary);

    if (url.pathname === "/svg") {
      const result = compileDocument(doc);
      return new Response(result.svg, {
        headers: { "Content-Type": "image/svg+xml" },
      });
    }

    if (url.pathname === "/json") {
      const result = compileDocument(doc);
      return Response.json({
        width: result.width,
        height: result.height,
        warnings: result.warnings,
      });
    }

    // Default: show the SVG inline in an HTML page
    const result = compileDocument(doc);
    const html = `<!DOCTYPE html>
<html>
<head><title>HTVG Cloudflare Workers Test</title></head>
<body style="display:flex;justify-content:center;padding:40px;background:#f0f0f0">
  ${result.svg}
</body>
</html>`;
    return new Response(html, {
      headers: { "Content-Type": "text/html" },
    });
  },
};
